# Assignment 1. Numpy Assignment

### Problem 1

In [1]:
import numpy as np

### Problem 2

In [2]:
array1 = np.arange(15, 41)
array1


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

In [3]:
array2 = np.arange(10, 26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

##### Both array1 and array2 intercept from 15 to 25. array1 has 26 elements and array2 has 16 elements. Unique numbers to array1 are all inegers from 26 to 40. Unique numbers in array2 are all integers from 10 to 14.

### Problem 3

In [4]:
even_array1 = np.arange(2,21,2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
even_array1.shape

(10,)

In [9]:
even_array2 = np.arange(34,43,2)
even_array2

array([34, 36, 38, 40, 42])

In [11]:
even_array2.shape

(5,)

In [13]:
matrix = np.stack((even_array1, even_array2)) ## Gives a ValueError because the arrays are not the same shape

ValueError: all input arrays must have the same shape

In [15]:
## reshape even_array2 with NaN values to match the shape of even_array1

for i in range(len(even_array1) - len(even_array2)):
    even_array2 = np.append(even_array2, np.nan)
    
even_array2

array([34., 36., 38., 40., 42., nan, nan, nan, nan, nan])

In [16]:
even_array2.shape

(10,)

In [18]:
matrix = np.stack((even_array1, even_array2))
matrix

array([[ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
       [34., 36., 38., 40., 42., nan, nan, nan, nan, nan]])

### Problem 4

In [23]:
prob_4 = np.arange(36)
prob_4.resize(6,6)
prob_4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
prob_4[2][1]

13

In [28]:
prob_4_1 = np.random.randn(5,2)
prob_4_1

array([[ 1.02205183, -0.77655373],
       [ 0.2663816 , -0.34838166],
       [ 0.14170691, -0.30695103],
       [-0.76668098,  1.91669184],
       [-1.77299199,  0.08740619]])

In [29]:
prob_4_1[4][1]

0.08740619093461748

### Problem 5

In [35]:
prob_4_1.max()

1.9166918360602412

In [36]:
prob_4_1.min()

-1.7729919872976274

In [37]:
prob_4_1.std()

0.9663348649628165

In [38]:
prob_4_1.var()

0.9338030712427049

In [39]:
prob_4_1.mean()

-0.05373210204065358